### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by ccccccmd** [personball/abplus-zero-template#1]
`2>D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1128,5): warning MSB3191: 无法创建目录“C:\Users\perso\source\projects\Test\Test.ZeroDemo\aspnet-core\src\Test.ZeroDemo.Application\”。对路径“C:\Users\perso\source\projects\Test\Test.ZeroDemo\aspnet-core\src\Test.ZeroDemo.Application\”的访问被拒绝。
`

`
CSC : error CS0016: 未能写入输出文件“C:\Users\perso\source\projects\Test\Test.ZeroDemo\aspnet-core\src\Test.ZeroDemo.Application\Test.ZeroDemo.Application.xml”--“未能找到路径“C:\Users\perso\source\projects\Test\Test.ZeroDemo\aspnet-core\src\Test.ZeroDemo.Application\Test.ZeroDemo.Application.xml”的一部分。”`

CLI生成的项目在`D:\myapp\`，怎么定位到`C:\Users`里了

**Comment by ccccccmd** [comment]
修改 两个 `scproj`里的`DocumentationFile`

 里两个 xml 的路径就解决了

**Comment by personball** [comment]
@ccccccmd 感谢反馈
