### ISSUE TITLE
angular模板中启动后请求AbpUserConfiguration/GetAll失败

### ISSUE THREAD

**Issue by SwimmingFish-WH** [personball/abplus-zero-template#12]
angular模板中启动后请求AbpUserConfiguration/GetAll失败
临时解决方案是在startup.service.ts文件的getAbpUserConfiguration方法中设置cultureCookie值
`
if (abp.utils.getCookieValue('Abp.Localization.CultureName') != null) {
      cultureCookie = abp.utils.getCookieValue('Abp.Localization.CultureName');
    }
   if (cultureCookie === '') {cultureCookie = 'zh-cn'; }//新增设置语言默认值

    return this.httpClient.get(`${AppConsts.remoteServiceBaseUrl}/AbpUserConfiguration/GetAll`, {
      headers: {
        Authorization: `Bearer ${abp.auth.getToken()}`,
        '.AspNetCore.Culture': cultureCookie,
        'Abp.TenantId': `${abp.multiTenancy.getTenantIdCookie()}`
      }

`

**Comment by personball** [comment]
@SwimmingFish-WH   默认 zh-cn 应改用 zh-Hans ，谢谢反馈，问题已修复，issue关闭。
