### ISSUE TITLE
angular里怎么调用微信

### ISSUE THREAD

**Issue by zhpengbj** [personball/abplus-zero-template#13]
TokenAuthController中增加的WechatH5Auth和WechatH5AuthCallback这2个方法，在前端angular里怎么调用？谢谢。

**Comment by personball** [comment]
WechatH5Auth 是重定向url，经后端处理后，再重定向到微信授权页，微信用户授权后，微信重定向回WechatH5AuthCallback，后端处理后，再重定向回 第一步的url中携带的targetUrl参数指定的前端页面地址。前端获取经加密后的encryptedCode，再调用 ExternalAuthenticate 方法换取accessToken。

具体认证协议请学习OAuth2.0
